version: '3.3'

services:
  backend:
    build:
      context: benchmark
      dockerfile: benchmark/Dockerfile
    ports:
      - 3000:5000
  frontend:
    build:
      context: frontend
      dockerfile: frontend/Dockerfile
    environment:
      NEXT_PUBLIC_BACKEND: 'http://localhost:8051/'
      NEXT_PUBLIC_MAPS_API_KEY: 23Wx5lgtGMfDkfMkCuF1
